"""The fixed part of the mock world: services, CMDB, routine changes and background incident families.

Nothing here is random. The generator (scripts/build_mock_data.py) combines it with the
hand-written problem stories (stories.py) and a seeded random generator.

Calibration taken from the real, anonymised ServiceNow event log (incident_event_log.csv,
24,918 incidents, 2016-2017). Only the statistics are used, never the records:
- reassignments per incident: 0 = 54%, 1 = 25%, 2 = 9%, 3 = 5%, 4+ = 7%
- about 1% of incidents are reopened
- 22% wait for the caller at least once, 1% wait for a vendor
- an incident is closed about 5 days after it is resolved (automatic closure)
- about 1.5% of incidents are linked to a problem; the largest cluster has 32 incidents
"""

REASSIGNMENT_WEIGHTS = {0: 54, 1: 25, 2: 9, 3: 5, 4: 4, 5: 3}
REOPEN_RATE = 0.01
AWAITING_CALLER_RATE = 0.22
AUTO_CLOSE_DAYS = 5

# The categories used for the root cause of an RCA (from the ServiceNow RCA export) and the
# bones of the Fishbone diagram (the IT version of the 6M categories).
ROOT_CAUSE_CATEGORIES = [
    "Software Defect",
    "Configuration Error",
    "Capacity / Resource Exhaustion",
    "Certificate / Credential Expiry",
    "Infrastructure Failure",
    "Third-Party / Vendor",
    "Process Gap",
]
FISHBONE_CATEGORIES = ["Change / Release", "Configuration", "Capacity", "Dependencies", "Monitoring", "Process"]

# --------------------------------------------------------------------------------------
# Services
# --------------------------------------------------------------------------------------
# team: the owner team and assignment group. reporters: who usually raises the incident.
# regions: the usual footprint. transactional: whether failed transactions can be counted.

SERVICES = {
    "Payment API": {
        "business": "Online Payments", "team": "Payments Platform Engineering", "prefix": "PAY",
        "hosts": ["payment-api-prod-01", "payment-api-prod-02", "payment-api-prod-03", "payment-api-prod-04"],
        "reporters": ["Incident Management", "Payments Operations", "Merchant Support"],
        "regions": [["eu-west-1", "eu-west-2"], ["eu-west-1"], ["eu-central-1"]],
        "transactional": True, "customers": (800, 16000),
    },
    "Auth Service": {
        "business": "User Authentication", "team": "IAM Engineering", "prefix": "AUTH",
        "hosts": ["auth-service-prod-01", "auth-service-prod-02", "auth-service-prod-03"],
        "reporters": ["Service Desk", "Incident Management", "Customer Identity Operations"],
        "regions": [["global"], ["eu-west-1"], ["us-east-1"]],
        "transactional": False, "customers": (1500, 40000),
    },
    "Billing Service": {
        "business": "Billing", "team": "Finance Engineering", "prefix": "BILL",
        "hosts": ["billing-service-prod-01", "billing-service-prod-02"],
        "reporters": ["Finance Operations", "Incident Management"],
        "regions": [["eu-west-1"], ["us-east-1"]],
        "transactional": True, "customers": (200, 6000),
    },
    "API Gateway": {
        "business": "Digital Channels", "team": "Core Platform", "prefix": "GW",
        "hosts": ["edge-proxy-prod-01", "edge-proxy-prod-02", "edge-proxy-prod-03", "edge-proxy-prod-04"],
        "reporters": ["Incident Management", "Network Operations Centre"],
        "regions": [["global"], ["eu-west-1", "eu-central-1"], ["us-east-1"]],
        "transactional": True, "customers": (3000, 60000),
    },
    "Settlement Service": {
        "business": "Core Banking", "team": "Treasury Engineering", "prefix": "SETTLE",
        "hosts": ["settlement-consumer-prod-01", "settlement-consumer-prod-02", "settlement-consumer-prod-03"],
        "reporters": ["Treasury Operations", "Incident Management"],
        "regions": [["eu-west-1"], ["global"]],
        "transactional": True, "customers": (50, 900),
    },
    "Customer Portal": {
        "business": "Customer Services", "team": "Digital Commerce Engineering", "prefix": "PORTAL",
        "hosts": ["portal-web-prod-01", "portal-web-prod-02", "portal-web-prod-03"],
        "reporters": ["Customer Experience", "Service Desk", "Incident Management"],
        "regions": [["eu-west-1", "eu-central-1"], ["eu-west-1"], ["global"]],
        "transactional": False, "customers": (1000, 30000),
    },
    "Notification Service": {
        "business": "Notifications", "team": "Messaging Platform", "prefix": "NOTIF",
        "hosts": ["notif-worker-prod-01", "notif-worker-prod-02", "rabbitmq-prod-01", "rabbitmq-prod-02"],
        "reporters": ["Digital Marketing Operations", "Service Desk"],
        "regions": [["global"], ["eu-west-1"], ["ap-southeast-1"]],
        "transactional": False, "customers": (2000, 80000),
    },
    "Payroll Service": {
        "business": "Payroll & HR", "team": "HR Systems Engineering", "prefix": "PAYROLL",
        "hosts": ["payroll-worker-prod-01", "payroll-worker-prod-02", "payroll-app-prod-01"],
        "reporters": ["Payroll Operations", "Service Desk"],
        "regions": [["eu-west-1"]],
        "transactional": False, "customers": (300, 5200),
    },
    "User Profile Service": {
        "business": "Customer Services", "team": "Customer Identity", "prefix": "USER",
        "hosts": ["user-profile-prod-01", "user-profile-prod-02"],
        "reporters": ["Customer Experience", "Incident Management"],
        "regions": [["eu-west-1"], ["global"]],
        "transactional": False, "customers": (500, 20000),
    },
    "Reporting Service": {
        "business": "Reporting", "team": "Data Platform", "prefix": "REP",
        "hosts": ["reporting-batch-prod-01", "reporting-batch-prod-02"],
        "reporters": ["Data Platform", "Finance Operations"],
        "regions": [["eu-west-1"], ["ap-southeast-1"]],
        "transactional": False, "customers": (20, 400),
    },
}

# --------------------------------------------------------------------------------------
# CMDB
# --------------------------------------------------------------------------------------
# (ci_id, name, type, service, owner_team, criticality)
# Payment API keeps exactly its three components and three relationships: the tests of the
# Payment API scenario rely on them.

CONFIG_ITEMS = [
    # Payment API
    ("CI-PAYMENT-API", "payment-api", "application", "Payment API", "Payments Platform Engineering", "high"),
    ("CI-PAYMENT-DB", "payment-postgresql", "database", "Payment API", "Database Engineering", "high"),
    ("CI-PAYMENT-QUEUE", "payment-retry-queue", "queue", "Payment API", "Payments Platform Engineering", "high"),
    # API Gateway
    ("CI-API-GATEWAY", "public-api-gateway", "gateway", "API Gateway", "Core Platform", "high"),
    ("CI-GW-EDGE-NODES", "edge-proxy-nodes", "host", "API Gateway", "Core Platform", "high"),
    ("CI-GW-WAF", "edge-waf-policy", "gateway", "API Gateway", "Security Engineering", "high"),
    ("CI-GW-RATE-LIMITER", "gateway-rate-limiter", "cache", "API Gateway", "Core Platform", "medium"),
    # Auth Service
    ("CI-AUTH-APP", "auth-service", "application", "Auth Service", "IAM Engineering", "high"),
    ("CI-AUTH-DB", "auth-postgresql", "database", "Auth Service", "Database Engineering", "high"),
    ("CI-SESSION-REDIS", "session-store-redis", "cache", "Auth Service", "IAM Engineering", "high"),
    ("CI-AUTH-EMAIL-QUEUE", "auth-email-queue", "queue", "Auth Service", "IAM Engineering", "medium"),
    # Billing Service
    ("CI-BILLING-APP", "billing-service", "application", "Billing Service", "Finance Engineering", "high"),
    ("CI-BILLING-DB", "billing-postgresql", "database", "Billing Service", "Finance Engineering", "high"),
    ("CI-BILLING-PDF", "invoice-pdf-renderer", "application", "Billing Service", "Finance Engineering", "medium"),
    ("CI-BILLING-SCHEDULER", "billing-job-scheduler", "application", "Billing Service", "Finance Engineering", "medium"),
    # Settlement Service
    ("CI-SETTLE-SERVICE", "settlement-consumer", "application", "Settlement Service", "Treasury Engineering", "high"),
    ("CI-SETTLE-DB", "settlement-ledger-db", "database", "Settlement Service", "Database Engineering", "high"),
    # Customer Portal
    ("CI-PORTAL-WEB", "customer-portal-web", "application", "Customer Portal", "Digital Commerce Engineering", "high"),
    ("CI-PORTAL-CDN", "customer-portal-cdn", "gateway", "Customer Portal", "Digital Commerce Engineering", "high"),
    ("CI-PORTAL-LOCK-REDIS", "portal-session-lock-redis", "cache", "Customer Portal", "Digital Commerce Engineering", "medium"),
    ("CI-PORTAL-SEARCH", "portal-search-index", "application", "Customer Portal", "Digital Commerce Engineering", "medium"),
    ("CI-PORTAL-CART-CACHE", "portal-cart-cache", "cache", "Customer Portal", "Digital Commerce Engineering", "medium"),
    # Notification Service
    ("CI-NOTIF-WORKER", "notification-worker", "application", "Notification Service", "Messaging Platform", "medium"),
    ("CI-NOTIF-MQ", "notification-rabbitmq", "queue", "Notification Service", "Messaging Platform", "high"),
    ("CI-NOTIF-BROKER-HOST", "rabbitmq-prod-hosts", "host", "Notification Service", "Platform Operations", "high"),
    ("CI-NOTIF-TEMPLATES", "notification-templates", "application", "Notification Service", "Messaging Platform", "low"),
    # Payroll Service
    ("CI-PAYROLL-APP", "payroll-portal-api", "application", "Payroll Service", "HR Systems Engineering", "high"),
    ("CI-PAYROLL-WORKER", "payroll-batch-workers", "application", "Payroll Service", "HR Systems Engineering", "high"),
    ("CI-PAYROLL-DB", "payroll-postgresql", "database", "Payroll Service", "Database Engineering", "high"),
    # User Profile Service
    ("CI-USER-PROFILE-APP", "user-profile-service", "application", "User Profile Service", "Customer Identity", "high"),
    ("CI-USER-PROFILE-DB", "user-profile-db", "database", "User Profile Service", "Database Engineering", "high"),
    ("CI-USER-PROFILE-CACHE", "user-profile-cache", "cache", "User Profile Service", "Customer Identity", "medium"),
    ("CI-AVATAR-STORAGE", "avatar-object-storage", "storage", "User Profile Service", "Customer Identity", "low"),
    # Reporting Service
    ("CI-REP-APP", "reporting-batch", "application", "Reporting Service", "Data Platform", "medium"),
    ("CI-REP-WAREHOUSE", "reporting-warehouse", "database", "Reporting Service", "Data Platform", "medium"),
    ("CI-REP-CACHE", "dashboard-cache", "cache", "Reporting Service", "Data Platform", "low"),
    ("CI-REP-INGEST", "reporting-ingestion-pipeline", "application", "Reporting Service", "Data Platform", "medium"),
    # Shared platforms
    ("CI-K8S-PROD", "k8s-prod-cluster", "host", "Kubernetes Platform", "Platform Operations", "high"),
    ("CI-COREDNS", "coredns", "application", "Kubernetes Platform", "Platform Operations", "high"),
    ("CI-CERT-MANAGER", "cert-manager", "application", "Kubernetes Platform", "Platform Operations", "high"),
    ("CI-KAFKA-CLUSTER", "kafka-prod-cluster", "queue", "Event Streaming Platform", "Streaming Platform Team", "high"),
    ("CI-SCHEMA-REGISTRY", "schema-registry", "application", "Event Streaming Platform", "Streaming Platform Team", "high"),
    ("CI-EGRESS-PROXY", "egress-proxy-firewall", "gateway", "Network Services", "Network Engineering", "high"),
    ("CI-LOG-PIPELINE", "fluent-bit-log-shipper", "application", "Observability Platform", "Observability Engineering", "medium"),
    # External vendors (managed through contracts, not by our teams)
    ("CI-CARD-ACQUIRER", "card-acquirer-gateway", "gateway", "External Vendors", "Vendor Management", "high"),
    ("CI-FRAUD-ENGINE", "fraud-scoring-provider", "application", "External Vendors", "Vendor Management", "high"),
    ("CI-FX-PROVIDER", "fx-rate-provider", "application", "External Vendors", "Vendor Management", "medium"),
    ("CI-TOKEN-VAULT", "card-tokenisation-vault", "application", "External Vendors", "Vendor Management", "high"),
    ("CI-MFA-PROVIDER", "otp-mfa-provider", "application", "External Vendors", "Vendor Management", "high"),
    ("CI-SMS-GATEWAY", "sms-gateway-provider", "gateway", "External Vendors", "Vendor Management", "medium"),
    ("CI-PUSH-PROVIDER", "mobile-push-provider", "gateway", "External Vendors", "Vendor Management", "medium"),
    ("CI-CLEARING-HOUSE", "clearing-house-link", "gateway", "External Vendors", "Vendor Management", "high"),
    ("CI-TAX-ENGINE", "tax-calculation-provider", "application", "External Vendors", "Vendor Management", "medium"),
    ("CI-BANK-SFTP", "bank-transfer-sftp", "storage", "External Vendors", "Vendor Management", "high"),
]

# (source_ci, target_ci, relationship_type): source depends on target.
RELATIONSHIPS = [
    # Payment API (unchanged)
    ("CI-PAYMENT-API", "CI-PAYMENT-DB", "connects_to"),
    ("CI-PAYMENT-API", "CI-PAYMENT-QUEUE", "connects_to"),
    ("CI-API-GATEWAY", "CI-PAYMENT-API", "connects_to"),
    # API Gateway
    ("CI-API-GATEWAY", "CI-GW-EDGE-NODES", "hosted_on"),
    ("CI-API-GATEWAY", "CI-GW-WAF", "depends_on"),
    ("CI-API-GATEWAY", "CI-GW-RATE-LIMITER", "depends_on"),
    ("CI-API-GATEWAY", "CI-CERT-MANAGER", "depends_on"),
    ("CI-API-GATEWAY", "CI-AUTH-APP", "connects_to"),
    ("CI-API-GATEWAY", "CI-USER-PROFILE-APP", "connects_to"),
    # Auth Service
    ("CI-AUTH-APP", "CI-AUTH-DB", "depends_on"),
    ("CI-AUTH-APP", "CI-SESSION-REDIS", "connects_to"),
    ("CI-AUTH-APP", "CI-AUTH-EMAIL-QUEUE", "connects_to"),
    ("CI-AUTH-APP", "CI-MFA-PROVIDER", "connects_to"),
    ("CI-AUTH-APP", "CI-K8S-PROD", "hosted_on"),
    # Billing Service
    ("CI-BILLING-APP", "CI-BILLING-DB", "depends_on"),
    ("CI-BILLING-APP", "CI-BILLING-PDF", "connects_to"),
    ("CI-BILLING-APP", "CI-TAX-ENGINE", "connects_to"),
    ("CI-BILLING-SCHEDULER", "CI-BILLING-DB", "depends_on"),
    ("CI-BILLING-PDF", "CI-K8S-PROD", "hosted_on"),
    # Settlement Service
    ("CI-SETTLE-SERVICE", "CI-KAFKA-CLUSTER", "connects_to"),
    ("CI-SETTLE-SERVICE", "CI-SCHEMA-REGISTRY", "depends_on"),
    ("CI-SETTLE-SERVICE", "CI-SETTLE-DB", "depends_on"),
    ("CI-SETTLE-SERVICE", "CI-CLEARING-HOUSE", "connects_to"),
    # Customer Portal
    ("CI-PORTAL-CDN", "CI-PORTAL-WEB", "connects_to"),
    ("CI-PORTAL-WEB", "CI-PORTAL-LOCK-REDIS", "connects_to"),
    ("CI-PORTAL-WEB", "CI-PORTAL-SEARCH", "connects_to"),
    ("CI-PORTAL-WEB", "CI-PORTAL-CART-CACHE", "connects_to"),
    ("CI-PORTAL-WEB", "CI-API-GATEWAY", "connects_to"),
    # Notification Service
    ("CI-NOTIF-WORKER", "CI-NOTIF-MQ", "connects_to"),
    ("CI-NOTIF-WORKER", "CI-NOTIF-TEMPLATES", "depends_on"),
    ("CI-NOTIF-WORKER", "CI-SMS-GATEWAY", "connects_to"),
    ("CI-NOTIF-WORKER", "CI-PUSH-PROVIDER", "connects_to"),
    ("CI-NOTIF-MQ", "CI-NOTIF-BROKER-HOST", "hosted_on"),
    # Payroll Service
    ("CI-PAYROLL-APP", "CI-PAYROLL-DB", "depends_on"),
    ("CI-PAYROLL-WORKER", "CI-PAYROLL-DB", "depends_on"),
    ("CI-PAYROLL-WORKER", "CI-BANK-SFTP", "connects_to"),
    ("CI-PAYROLL-WORKER", "CI-K8S-PROD", "hosted_on"),
    # User Profile Service
    ("CI-USER-PROFILE-APP", "CI-USER-PROFILE-DB", "depends_on"),
    ("CI-USER-PROFILE-APP", "CI-USER-PROFILE-CACHE", "connects_to"),
    ("CI-USER-PROFILE-APP", "CI-AVATAR-STORAGE", "connects_to"),
    # Reporting Service
    ("CI-REP-APP", "CI-REP-WAREHOUSE", "depends_on"),
    ("CI-REP-APP", "CI-REP-CACHE", "connects_to"),
    ("CI-REP-APP", "CI-COREDNS", "connects_to"),
    ("CI-REP-INGEST", "CI-REP-WAREHOUSE", "connects_to"),
    ("CI-REP-INGEST", "CI-KAFKA-CLUSTER", "connects_to"),
    # Shared platforms
    ("CI-COREDNS", "CI-K8S-PROD", "hosted_on"),
    ("CI-CERT-MANAGER", "CI-K8S-PROD", "hosted_on"),
    ("CI-SCHEMA-REGISTRY", "CI-KAFKA-CLUSTER", "connects_to"),
    ("CI-LOG-PIPELINE", "CI-K8S-PROD", "hosted_on"),
]

# --------------------------------------------------------------------------------------
# Routine changes
# --------------------------------------------------------------------------------------
# The ordinary work of every team: releases, patching, certificate renewals, config tweaks.
# They are innocent, and they fall into incident windows by chance, exactly like in reality.
# (service, ci_id, type, risk, every_days, title, description, versioned)

ROUTINE_CHANGES = [
    ("Payment API", "CI-PAYMENT-API", "normal", "medium", 18, "Deploy Payment API v{version}",
     "Scheduled release: bug fixes and merchant reporting improvements.", True),
    ("Payment API", "CI-PAYMENT-DB", "standard", "low", 45, "Apply PostgreSQL minor patch on payment-postgresql",
     "Rolling minor version patch on the replicas, then switchover.", False),
    ("Auth Service", "CI-AUTH-APP", "normal", "medium", 21, "Deploy Auth Service v{version}",
     "Scheduled release: login page fixes and dependency updates.", True),
    ("Auth Service", "CI-SESSION-REDIS", "standard", "low", 60, "Patch session-store-redis nodes",
     "Rolling OS and Redis patch release, one node at a time.", False),
    ("Billing Service", "CI-BILLING-APP", "normal", "medium", 21, "Deploy Billing Service v{version}",
     "Scheduled release: invoice layout and email wording changes.", True),
    ("Billing Service", "CI-BILLING-DB", "standard", "low", 60, "Vacuum and analyse billing-postgresql",
     "Routine maintenance on the billing database during the weekend window.", False),
    ("API Gateway", "CI-API-GATEWAY", "normal", "medium", 14, "Update API gateway routing configuration",
     "Add routes for new partner endpoints; no change to existing routes.", False),
    ("API Gateway", "CI-GW-EDGE-NODES", "standard", "low", 30, "Monthly OS patching of edge proxy nodes",
     "Rolling kernel and OpenSSL patches, nodes drained one by one.", False),
    ("API Gateway", "CI-GW-WAF", "standard", "low", 35, "Update WAF managed rule set",
     "Vendor managed rule set update in detection mode first.", False),
    ("Settlement Service", "CI-SETTLE-SERVICE", "normal", "medium", 28, "Deploy Settlement Service v{version}",
     "Scheduled release: reconciliation report changes.", True),
    ("Customer Portal", "CI-PORTAL-WEB", "normal", "medium", 10, "Customer Portal release {version}",
     "Frontend and backend-for-frontend release: content and styling updates.", True),
    ("Customer Portal", "CI-PORTAL-CDN", "standard", "low", 40, "Update CDN edge configuration",
     "Refresh TLS ciphers list and security headers on the CDN.", False),
    ("Notification Service", "CI-NOTIF-WORKER", "normal", "low", 24, "Deploy Notification Service v{version}",
     "Scheduled release: new templates and provider client updates.", True),
    ("Notification Service", "CI-NOTIF-BROKER-HOST", "standard", "low", 45, "Patch RabbitMQ broker hosts",
     "Rolling OS patching of the broker hosts.", False),
    ("Payroll Service", "CI-PAYROLL-APP", "normal", "medium", 30, "Deploy Payroll Service v{version}",
     "Scheduled release: payslip layout and self-service fixes.", True),
    ("User Profile Service", "CI-USER-PROFILE-APP", "normal", "medium", 25, "Deploy User Profile Service v{version}",
     "Scheduled release: profile editing improvements.", True),
    ("Reporting Service", "CI-REP-APP", "normal", "low", 30, "Deploy Reporting Service v{version}",
     "Scheduled release: new finance dashboards.", True),
    ("Kubernetes Platform", "CI-K8S-PROD", "standard", "medium", 30, "Monthly node image upgrade on k8s-prod-cluster",
     "Rolling replacement of worker nodes with the patched image.", False),
    ("Kubernetes Platform", "CI-CERT-MANAGER", "standard", "low", 90, "Upgrade cert-manager minor version",
     "Minor version upgrade of cert-manager and its CRDs.", False),
    ("Event Streaming Platform", "CI-KAFKA-CLUSTER", "standard", "medium", 45, "Rolling restart of kafka-prod-cluster brokers",
     "Apply broker configuration and JVM patch with a rolling restart.", False),
    ("Network Services", "CI-EGRESS-PROXY", "standard", "low", 40, "Update egress firewall allowlist",
     "Add approved destinations requested by application teams.", False),
    ("Observability Platform", "CI-LOG-PIPELINE", "standard", "low", 50, "Upgrade fluent-bit log shipper",
     "Rolling upgrade of the log shipper daemonset.", False),
]

# --------------------------------------------------------------------------------------
# Background incident families
# --------------------------------------------------------------------------------------
# One family is one kind of failure that happens now and then on a service. Its incidents are
# the background of the data: realistic, unrelated to the problem stories, and sometimes
# similar enough in wording to be a distractor for the search.
#
# Titles and descriptions say what people saw, never why. The `rca` block is the cause, used
# only for the past RCA documents written for some families.
#
# hours: when the family usually happens (business, peak, night, any).
# change: a change made shortly before each incident, when the family is caused by one.
# logs: (level, error_type, message templates). Placeholders: {host} {n} {ms} {pct} {id}.

FAMILIES = [
    # ---------------------------------------------------------------- Payment API
    {
        "key": "pay_tokenisation", "service": "Payment API", "ci": "CI-TOKEN-VAULT", "count": 9,
        "severity": (1, 4, 4, 1), "hours": "business", "vendor": True,
        "titles": ["Card tokenisation requests failing at checkout", "Checkout fails while saving card details",
                   "Customers cannot store cards during payment"],
        "descriptions": ["A share of checkout attempts failed when the card was sent for tokenisation. Customers saw a generic payment error.",
                         "Saving a card during checkout failed for part of the customers. Payments without a stored card completed normally."],
        "symptoms": ["Tokenisation service errors", "Checkout failures", "HTTP 502 from tokenisation endpoint"],
        "mitigation": "Retried failed tokenisations through the secondary vault region.",
        "logs": [("ERROR", "TokenisationError", ["POST /v2/tokens returned 502 Bad Gateway from card-tokenisation-vault (attempt 3/3)",
                                                 "Tokenisation failed for order ORD-{id}: upstream vault unavailable"]),
                 ("WARN", "UpstreamLatency", ["card-tokenisation-vault p99 latency {ms}ms exceeds 1000ms threshold"])],
        "rca": {
            "category": "Third-Party / Vendor",
            "summary": "Card tokenisation calls failed for a share of checkouts while the vault provider ran a maintenance with reduced capacity.",
            "root_cause": "The tokenisation vendor moved traffic to a reduced-capacity cluster during unannounced maintenance. Our client had no failover to the secondary region configured, so requests failed instead of being retried there.",
            "whys": [("Why did checkouts fail?", "Card tokenisation calls returned HTTP 502."),
                     ("Why did tokenisation return 502?", "The vendor's primary cluster was overloaded during its maintenance."),
                     ("Why did the overload reach our customers?", "The client sent all traffic to the primary region only."),
                     ("Why was there no regional failover?", "The failover setting was never enabled after the vendor onboarding."),
                     ("Why was that not noticed?", "Vendor failover was not part of the onboarding checklist.")],
            "factors": {"Dependencies": "Single region dependency on the tokenisation vendor.",
                        "Process": "Vendor maintenance notices were not tracked by the Payments team.",
                        "Monitoring": "Alert fired on checkout failures only, not on vault latency."},
            "corrective": "Enabled automatic failover to the secondary vault region.",
            "preventive": "Added vendor failover to the onboarding checklist and subscribed the on-call team to vendor maintenance notices.",
        },
    },
    {
        "key": "pay_fraud", "service": "Payment API", "ci": "CI-FRAUD-ENGINE", "count": 8,
        "severity": (0, 3, 5, 2), "hours": "any", "vendor": True,
        "titles": ["Payment approvals delayed during checkout", "Slow payment confirmation for card orders",
                   "Authorisations completing several seconds late"],
        "descriptions": ["Payment approvals queued behind the fraud check. Authorisations completed, but several seconds slower than normal.",
                         "Customers waited a long time for the payment confirmation page. Some abandoned the checkout."],
        "symptoms": ["Fraud check latency spike", "Approval queue backlog", "Checkout confirmation delay"],
        "mitigation": "Bypassed fraud scoring for low-risk transactions temporarily.",
        "logs": [("ERROR", "FraudScoringTimeout", ["Fraud score request to fraud-scoring-provider timed out after 3000ms (order ORD-{id})"]),
                 ("WARN", "ApprovalQueueBacklog", ["Approval queue depth {n} above threshold 1000"])],
    },
    {
        "key": "pay_acquirer", "service": "Payment API", "ci": "CI-CARD-ACQUIRER", "count": 8,
        "severity": (1, 4, 3, 0), "hours": "peak", "vendor": True,
        "titles": ["Card authorisations timing out at the acquirer", "Checkout failures for card payments during busy hours",
                   "Payment API reports timeouts to the card network"],
        "descriptions": ["Outbound authorisation calls to the card acquirer intermittently timed out, mostly during the busiest hours.",
                         "Card payments failed with a timeout for part of the customers; wallets and bank transfers were not affected."],
        "symptoms": ["Gateway timeout errors", "Increased checkout abandonment", "Circuit breaker opened"],
        "mitigation": "Failed over to the secondary acquirer endpoint.",
        "logs": [("ERROR", "AcquirerTimeout", ["Authorisation request to card-acquirer-gateway timed out after 10000ms"]),
                 ("WARN", "CircuitBreakerOpen", ["Circuit breaker acquirer-primary OPEN after {pct}% failures in 30s"])],
        "rca": {
            "category": "Third-Party / Vendor",
            "summary": "Card authorisations timed out at peak hours because the acquirer throttled connections above the contracted rate.",
            "root_cause": "Peak traffic exceeded the concurrent connection limit agreed with the acquirer. The acquirer queued the extra connections and our 10 second timeout expired.",
            "whys": [("Why did card payments fail?", "Authorisation calls to the acquirer timed out."),
                     ("Why did they time out?", "The acquirer queued connections above the contracted limit."),
                     ("Why were we above the limit?", "Peak traffic grew 40% since the contract was sized."),
                     ("Why was the limit not raised?", "Capacity reviews did not include vendor contract limits.")],
            "factors": {"Capacity": "Contracted connection limit too low for current peak.",
                        "Dependencies": "Single acquirer for card payments.",
                        "Process": "Vendor limits missing from capacity planning."},
            "corrective": "Raised the contracted limit and enabled the secondary acquirer for overflow traffic.",
            "preventive": "Quarterly capacity review now includes every vendor contract limit.",
        },
    },
    {
        "key": "pay_duplicate", "service": "Payment API", "ci": "CI-PAYMENT-API", "count": 7,
        "severity": (0, 4, 3, 0), "hours": "business",
        "titles": ["Customers report duplicate card charges", "Some card payments charged twice",
                   "Merchants see duplicated payment captures"],
        "descriptions": ["Merchants and customers reported that some card payments were charged twice.",
                         "Finance found duplicated captures for a small share of orders paid from the mobile app."],
        "symptoms": ["Duplicate charge reports", "Idempotency key collisions", "Merchant refund requests"],
        "mitigation": "Reversed the duplicate charges and blocked retries without an idempotency key.",
        "logs": [("WARN", "DuplicateCapture", ["Capture for order ORD-{id} already exists; second capture accepted"]),
                 ("ERROR", "IdempotencyConflict", ["Idempotency key missing on retried request from mobile-app/7.{n}"])],
        "rca": {
            "category": "Software Defect",
            "summary": "A mobile app retry sent payment requests again without the idempotency key, so the Payment API processed them twice.",
            "root_cause": "The mobile app network layer retried timed-out payment requests but built a new request object without the idempotency header. The Payment API accepted the retry as a new payment.",
            "whys": [("Why were customers charged twice?", "The Payment API captured the same order twice."),
                     ("Why did it capture twice?", "The second request had no idempotency key, so it looked new."),
                     ("Why was the key missing?", "The app retry logic rebuilt the request without the header."),
                     ("Why was that not caught?", "Integration tests did not cover retries after a timeout.")],
            "factors": {"Change / Release": "Mobile app release changed the network retry layer.",
                        "Configuration": "The API accepted payments without an idempotency key.",
                        "Process": "No contract test between the mobile app and the Payment API."},
            "corrective": "Made the idempotency key mandatory on payment requests and refunded duplicates.",
            "preventive": "Added a contract test for retries between the mobile app and the Payment API.",
        },
    },
    {
        "key": "pay_webhook", "service": "Payment API", "ci": "CI-PAYMENT-QUEUE", "count": 7,
        "severity": (0, 2, 4, 2), "hours": "any",
        "titles": ["Merchant payment webhooks delivered late", "Merchants missing payment confirmation callbacks",
                   "Webhook retry queue growing for some merchants"],
        "descriptions": ["Payment confirmation webhooks to some merchants were retried repeatedly and delivered late.",
                         "A few merchants reported that payment confirmations arrived hours late."],
        "symptoms": ["Webhook delivery failures", "Webhook retry queue growth", "Merchant reconciliation gaps"],
        "mitigation": "Paused retries to the failing merchant endpoints and replayed the queue later.",
        "logs": [("ERROR", "WebhookDeliveryFailed", ["Webhook POST to merchant endpoint returned 503 (merchant_id=M-{id})"]),
                 ("WARN", "WebhookRetryBacklog", ["Webhook retry backlog {n} messages, oldest 42 minutes"])],
    },
    {
        "key": "pay_fx", "service": "Payment API", "ci": "CI-FX-PROVIDER", "count": 6,
        "severity": (0, 1, 4, 3), "hours": "any", "vendor": True,
        "titles": ["Slow checkout for payments in foreign currency", "Non-EUR payments confirm slowly",
                   "Currency conversion delays at checkout"],
        "descriptions": ["Payments in non-EUR currencies took longer to confirm because the exchange rate lookup was slow.",
                         "Customers paying in GBP and USD waited several seconds longer at checkout."],
        "symptoms": ["FX lookup latency spike", "Checkout confirmation delay"],
        "mitigation": "Switched to the cached exchange rate table temporarily.",
        "logs": [("ERROR", "FxRateTimeout", ["FX rate lookup for GBP/EUR timed out after 2000ms"]),
                 ("WARN", "FxCacheStale", ["Using FX rates older than 15 minutes for {n} requests"])],
    },
    {
        "key": "pay_flag", "service": "Payment API", "ci": "CI-PAYMENT-API", "count": 6,
        "severity": (1, 3, 2, 0), "hours": "business",
        "change": {"title": "Enable feature flag instalments_v2 for all merchants", "type": "standard", "risk": "low",
                   "description": "Roll out the new instalment plans to every merchant through the feature flag service.",
                   "ci": "CI-PAYMENT-API", "lead": (15, 70)},
        "titles": ["Payment API returning errors for part of checkouts", "Checkout errors for some merchants",
                   "Error rate increase on the Payment API"],
        "descriptions": ["Error rate on the Payment API rose for a fraction of checkout attempts; other requests completed normally.",
                         "Some merchants reported checkout errors while others were not affected."],
        "symptoms": ["HTTP 500 responses from Payment API", "Checkout failures"],
        "mitigation": "Disabled the new feature flag and monitored recovery.",
        "logs": [("ERROR", "UnhandledException", ["NullPointerException in InstalmentPlanResolver.resolve (merchant M-{id})"]),
                 ("WARN", "FeatureFlagEvaluation", ["Flag instalments_v2 evaluated true for merchant without instalment config"])],
        "rca": {
            "category": "Configuration Error",
            "summary": "Enabling a feature flag for all merchants sent requests to a code path that needs configuration most merchants did not have.",
            "root_cause": "The instalments_v2 flag was switched on globally. Merchants without instalment settings hit a null value in the plan resolver and the request failed with HTTP 500.",
            "whys": [("Why did checkouts fail?", "The Payment API threw a NullPointerException for some merchants."),
                     ("Why the exception?", "The instalment resolver read settings that did not exist for those merchants."),
                     ("Why were they on that code path?", "The feature flag was enabled for all merchants at once."),
                     ("Why at once?", "The flag rollout had no staged percentage plan.")],
            "factors": {"Change / Release": "Global feature flag rollout.",
                        "Configuration": "Missing default for merchants without instalment settings.",
                        "Process": "Feature flag changes were raised as standard changes without review."},
            "corrective": "Disabled the flag and added a default for merchants without instalment settings.",
            "preventive": "Feature flag rollouts above 10% of merchants now require a normal change with a staged plan.",
        },
    },
    # ---------------------------------------------------------------- Auth Service
    {
        "key": "auth_mfa", "service": "Auth Service", "ci": "CI-MFA-PROVIDER", "count": 9,
        "severity": (1, 4, 3, 1), "hours": "any", "vendor": True,
        "titles": ["Users not receiving one-time login codes", "MFA verification failing for part of users",
                   "Sign-in blocked at the second factor step"],
        "descriptions": ["Users could not complete sign-in because one-time codes were not delivered or were rejected.",
                         "The second factor step failed for part of the users; support calls increased quickly."],
        "symptoms": ["MFA verification failures", "Login abandonment increase", "Support call spike"],
        "mitigation": "Enabled the fallback MFA channel temporarily.",
        "logs": [("ERROR", "MfaProviderError", ["OTP send request to otp-mfa-provider returned 503 Service Unavailable"]),
                 ("WARN", "MfaFallback", ["Falling back to e-mail OTP for {n} users in the last 5 minutes"])],
        "rca": {
            "category": "Third-Party / Vendor",
            "summary": "The one-time password provider had a regional outage and our fallback channel had to be switched on by hand.",
            "root_cause": "The OTP provider's EU region was unavailable for 70 minutes. The automatic fallback to the e-mail channel was disabled after a false alarm the year before.",
            "whys": [("Why could users not sign in?", "One-time codes were not delivered."),
                     ("Why were they not delivered?", "The OTP provider returned 503 for the EU region."),
                     ("Why did the fallback not start by itself?", "Automatic fallback was disabled."),
                     ("Why was it disabled?", "A past false alarm triggered it wrongly and it was never re-enabled.")],
            "factors": {"Dependencies": "Single OTP provider region.",
                        "Configuration": "Automatic fallback switched off.",
                        "Monitoring": "No synthetic check for OTP delivery."},
            "corrective": "Re-enabled the automatic fallback with a stricter trigger.",
            "preventive": "Added a synthetic OTP delivery check every 5 minutes.",
        },
    },
    {
        "key": "auth_lockout", "service": "Auth Service", "ci": "CI-AUTH-APP", "count": 7,
        "severity": (0, 2, 4, 2), "hours": "business",
        "titles": ["Legitimate users locked out of their accounts", "Unexpected account lockouts reported to the service desk",
                   "Customers locked out after one or two attempts"],
        "descriptions": ["Several users were locked out after very few failed attempts; support calls increased.",
                         "The service desk received many calls from users whose accounts were locked without reason."],
        "symptoms": ["Unexpected account lockouts", "Support escalation spike"],
        "mitigation": "Unlocked the affected accounts and raised the lockout threshold.",
        "logs": [("WARN", "AccountLocked", ["Account locked after 3 failed attempts (policy brute_force_v4, user U-{id})"]),
                 ("ERROR", "LoginRejected", ["Login rejected for locked account U-{id}"])],
    },
    {
        "key": "auth_jwks", "service": "Auth Service", "ci": "CI-AUTH-APP", "count": 7,
        "severity": (1, 3, 3, 0), "hours": "any",
        "change": {"title": "Rotate token signing keys", "type": "standard", "risk": "low",
                   "description": "Scheduled rotation of the JWT signing key pair.", "ci": "CI-AUTH-APP", "lead": (20, 110)},
        "titles": ["Services receiving intermittent 401 responses", "Valid tokens rejected by downstream services",
                   "Intermittent authentication errors across several applications"],
        "descriptions": ["Several services calling the Auth Service received 401 responses for tokens that should have been valid.",
                         "Users were asked to sign in again on several applications within a short period."],
        "symptoms": ["Intermittent 401 responses", "Token cache miss spike", "Forced re-login spike"],
        "mitigation": "Cleared the token key cache and restarted the affected instances.",
        "logs": [("ERROR", "TokenValidationFailed", ["JWT validation failed: kid 'k-{id}' not found in JWKS cache"]),
                 ("WARN", "JwksRefreshSkipped", ["JWKS cache refresh skipped, next refresh in 3600s"])],
        "rca": {
            "category": "Configuration Error",
            "summary": "After a signing key rotation, several services kept an old key list and rejected new tokens.",
            "root_cause": "The key list cache in downstream services refreshed every 60 minutes, while the old key was removed 10 minutes after rotation. Tokens signed with the new key were rejected until the caches refreshed.",
            "whys": [("Why did services return 401?", "They rejected tokens signed with the new key."),
                     ("Why?", "Their cached key list did not contain the new key yet."),
                     ("Why was the cache outdated?", "The cache refreshed only every 60 minutes."),
                     ("Why did that matter?", "The rotation removed the old key after only 10 minutes.")],
            "factors": {"Change / Release": "Key rotation procedure.",
                        "Configuration": "Cache refresh interval longer than the key overlap period.",
                        "Process": "Rotation runbook did not mention downstream caches."},
            "corrective": "Kept both keys published for 24 hours after each rotation.",
            "preventive": "Downstream services now refresh the key list when they meet an unknown key id.",
        },
    },
    {
        "key": "auth_peak", "service": "Auth Service", "ci": "CI-AUTH-DB", "count": 8,
        "severity": (0, 2, 4, 2), "hours": "peak",
        "titles": ["Slow logins during the morning peak", "Login and token refresh slow at peak time",
                   "Sign-in takes several seconds for many users"],
        "descriptions": ["Login and token refresh requests became slow during the morning peak.",
                         "Users waited several seconds to sign in; some retried and made the load worse."],
        "symptoms": ["Elevated login latency", "Authentication retries"],
        "mitigation": "Scaled out the Auth Service replicas.",
        "logs": [("WARN", "SlowRequest", ["POST /oauth/token took {ms}ms"]),
                 ("ERROR", "DbPoolTimeout", ["Timeout waiting for a connection from pool auth-db after 5000ms"])],
    },
    {
        "key": "auth_reset_mail", "service": "Auth Service", "ci": "CI-AUTH-EMAIL-QUEUE", "count": 5,
        "severity": (0, 0, 3, 3), "hours": "any",
        "titles": ["Password reset e-mails arriving late", "Users waiting for password reset e-mails"],
        "descriptions": ["Password reset e-mails were delayed by up to an hour, causing a spike in support contacts."],
        "symptoms": ["Delayed reset email delivery", "Support ticket spike"],
        "mitigation": "Increased the e-mail queue worker count.",
        "logs": [("WARN", "EmailQueueBacklog", ["auth-email-queue depth {n}, oldest message 38 minutes"]),
                 ("ERROR", "SmtpTimeout", ["SMTP relay timed out after 30000ms"])],
    },
    {
        "key": "auth_session_drop", "service": "Auth Service", "ci": "CI-SESSION-REDIS", "count": 5,
        "severity": (0, 2, 3, 0), "hours": "any",
        "titles": ["Users signed out unexpectedly", "Active sessions lost for a group of users"],
        "descriptions": ["A group of users was signed out and had to log in again. Login itself worked.",
                         "Customers reported being logged out in the middle of their session."],
        "symptoms": ["Session store connection errors", "Forced re-login spike"],
        "mitigation": "Failed over to the session store replica.",
        "logs": [("ERROR", "SessionStoreConnection", ["Unable to connect to session-redis-prod-01:6379: connection reset by peer"]),
                 ("WARN", "SessionNotFound", ["Session not found for token (user U-{id}); forcing re-login"])],
    },
    # ---------------------------------------------------------------- Billing Service
    {
        "key": "bill_pdf", "service": "Billing Service", "ci": "CI-BILLING-PDF", "count": 8,
        "severity": (0, 2, 4, 2), "hours": "night",
        "titles": ["Invoice PDFs not generated for large accounts", "Invoice documents missing for business customers",
                   "Invoice delivery delayed for large accounts"],
        "descriptions": ["Invoice PDF generation timed out for accounts with many invoice lines.",
                         "Large business customers did not receive their invoice document on time."],
        "symptoms": ["PDF generation timeouts", "Invoice delivery delay"],
        "mitigation": "Raised the rendering timeout and added renderer workers.",
        "logs": [("ERROR", "PdfRenderTimeout", ["Rendering invoice INV-{id} ({n} lines) exceeded 120s"]),
                 ("WARN", "RenderQueueBacklog", ["PDF render queue backlog {n} documents"])],
        "rca": {
            "category": "Capacity / Resource Exhaustion",
            "summary": "PDF rendering for invoices with thousands of lines ran out of memory and timed out.",
            "root_cause": "The renderer loaded all invoice lines into one HTML page. For accounts above 1,500 lines the headless browser ran out of memory and was restarted, so the job hit its timeout.",
            "whys": [("Why were invoices missing?", "PDF generation timed out."),
                     ("Why did it time out?", "The renderer process restarted while rendering."),
                     ("Why did it restart?", "It ran out of memory on very large invoices."),
                     ("Why so much memory?", "All lines were rendered into a single page.")],
            "factors": {"Capacity": "Renderer memory limit sized for small invoices.",
                        "Change / Release": "Large enterprise customers onboarded without a load test.",
                        "Monitoring": "No alert on renderer restarts."},
            "corrective": "Split large invoices into pages of 500 lines.",
            "preventive": "Added renderer restart alerting and a load test with the largest account.",
        },
    },
    {
        "key": "bill_rounding", "service": "Billing Service", "ci": "CI-BILLING-APP", "count": 6,
        "severity": (0, 1, 4, 1), "hours": "business",
        "change": {"title": "Deploy Billing Service rounding update", "type": "normal", "risk": "medium",
                   "description": "Align invoice rounding with the new multi-currency rules.", "ci": "CI-BILLING-APP", "lead": (60, 600)},
        "titles": ["Invoice totals differ from line items", "Customers report small invoice total differences",
                   "Reconciliation flags cent differences on invoices"],
        "descriptions": ["Some multi-currency invoices showed totals one or two cents different from the sum of their lines.",
                         "Finance reconciliation flagged small differences on a batch of invoices."],
        "symptoms": ["Invoice total mismatch reports", "Reconciliation discrepancy alerts"],
        "mitigation": "Reverted the rounding change and reissued the affected invoices.",
        "logs": [("WARN", "ReconciliationMismatch", ["Invoice INV-{id} total differs from sum of lines by 0.01"]),
                 ("ERROR", "ReconciliationFailed", ["Reconciliation batch finished with {n} mismatches"])],
    },
    {
        "key": "bill_dunning", "service": "Billing Service", "ci": "CI-BILLING-SCHEDULER", "count": 6,
        "severity": (0, 0, 4, 2), "hours": "night",
        "titles": ["Customers received two payment reminders", "Duplicate overdue payment notices sent"],
        "descriptions": ["Customers with overdue invoices received the same reminder twice in one night."],
        "symptoms": ["Duplicate dunning notices", "Customer complaint spike"],
        "mitigation": "Serialised the dunning job schedule.",
        "logs": [("WARN", "JobOverlap", ["dunning-daily started while the previous run is still active"]),
                 ("ERROR", "DuplicateNotice", ["Reminder already sent today for account A-{id}"])],
    },
    {
        "key": "bill_release", "service": "Billing Service", "ci": "CI-BILLING-APP", "count": 6,
        "severity": (0, 2, 3, 1), "hours": "business",
        "change": {"title": "Deploy Billing Service v{version}", "type": "normal", "risk": "medium",
                   "description": "Release with the new payment plan screens.", "ci": "CI-BILLING-APP", "lead": (15, 90)},
        "titles": ["Billing API returning server errors", "Billing screens failing to load",
                   "Errors when customers open their invoices"],
        "descriptions": ["A subset of billing requests returned server errors shortly after the scheduled release.",
                         "Customers could not open some invoices; the billing API returned HTTP 500."],
        "symptoms": ["HTTP 500 responses from Billing Service"],
        "mitigation": "Rolled back to the previous Billing Service version.",
        "logs": [("ERROR", "UnhandledException", ["SQLGrammarException: column payment_plan_id does not exist"]),
                 ("WARN", "SlowRequest", ["GET /invoices/{id} took {ms}ms"])],
    },
    {
        "key": "bill_tax", "service": "Billing Service", "ci": "CI-TAX-ENGINE", "count": 5,
        "severity": (0, 1, 3, 1), "hours": "any", "vendor": True,
        "titles": ["Invoices failing tax calculation", "Invoice generation stopped for some countries"],
        "descriptions": ["A subset of invoices could not be generated because the tax calculation failed."],
        "symptoms": ["Tax calculation errors", "Invoice generation failures"],
        "mitigation": "Refreshed the tax rate table and reprocessed the failed invoices.",
        "logs": [("ERROR", "TaxEngineError", ["Tax quote failed: rate table version not found for country code {id}"])],
    },
    {
        "key": "bill_recon", "service": "Billing Service", "ci": "CI-BILLING-SCHEDULER", "count": 5,
        "severity": (0, 0, 3, 3), "hours": "night",
        "titles": ["Billing reconciliation running late", "Nightly billing checkpoints behind schedule"],
        "descriptions": ["The nightly invoice reconciliation checkpoints ran behind schedule."],
        "symptoms": ["Reconciliation checkpoint delay", "Batch job backlog"],
        "mitigation": "Increased batch worker parallelism temporarily.",
        "logs": [("WARN", "CheckpointDelay", ["Checkpoint {n} reached 47 minutes late"]),
                 ("ERROR", "BatchTimeout", ["Reconciliation step exceeded 3600s"])],
    },
    # ---------------------------------------------------------------- API Gateway
    {
        "key": "gw_waf", "service": "API Gateway", "ci": "CI-GW-WAF", "count": 7,
        "severity": (1, 3, 3, 0), "hours": "business",
        "change": {"title": "Enable new WAF rule set in blocking mode", "type": "standard", "risk": "low",
                   "description": "Move the latest WAF rules from detection to blocking mode.", "ci": "CI-GW-WAF", "lead": (10, 60)},
        "titles": ["Legitimate requests blocked with HTTP 403", "Partners report 403 errors on the public API",
                   "Customers blocked when saving their profile"],
        "descriptions": ["A class of legitimate requests was rejected with HTTP 403 by the gateway.",
                         "Several partners reported that valid API calls started failing with 403."],
        "symptoms": ["Unexpected 403 responses", "Blocked legitimate traffic"],
        "mitigation": "Rolled back the new WAF rule.",
        "logs": [("WARN", "WafBlock", ["Request blocked by rule 942100 (SQL injection pattern) path=/api/v1/profile"]),
                 ("ERROR", "ClientRejected", ["{n} requests rejected with 403 in the last minute"])],
        "rca": {
            "category": "Configuration Error",
            "summary": "A WAF rule moved to blocking mode matched normal profile updates that contain apostrophes.",
            "root_cause": "Rule 942100 treats an apostrophe followed by a keyword as SQL injection. Names like O'Connor in profile updates matched it, and the rule was switched to blocking without reviewing the detection-mode hits.",
            "whys": [("Why were requests blocked?", "WAF rule 942100 returned 403."),
                     ("Why did it match?", "Normal names with apostrophes looked like SQL injection."),
                     ("Why was it blocking?", "It was moved to blocking mode."),
                     ("Why was the risk missed?", "Detection-mode hits were not reviewed before the switch.")],
            "factors": {"Change / Release": "Rule set switched to blocking.",
                        "Process": "No review of detection-mode results.",
                        "Monitoring": "403 rate was not alerted per route."},
            "corrective": "Added an exclusion for the profile name fields.",
            "preventive": "WAF rules stay one week in detection mode and their hits are reviewed before blocking.",
        },
    },
    {
        "key": "gw_5xx", "service": "API Gateway", "ci": "CI-API-GATEWAY", "count": 7,
        "severity": (1, 3, 3, 0), "hours": "peak",
        "titles": ["Gateway returning 502 and 504 errors", "Short spike of 5xx errors on the public API",
                   "Public API errors during a traffic peak"],
        "descriptions": ["The gateway returned an elevated rate of 5xx responses for a short window while traffic was well above normal.",
                         "Clients received 502 and 504 errors from the public API for about twenty minutes."],
        "symptoms": ["5xx error rate spike", "Upstream timeout warnings"],
        "mitigation": "Restarted the affected gateway instances and rebalanced traffic.",
        "logs": [("ERROR", "UpstreamTimeout", ["upstream timed out (110: Connection timed out) while reading response header from upstream"]),
                 ("WARN", "WorkerConnections", ["{n} worker_connections are not enough"])],
    },
    {
        "key": "gw_eviction", "service": "API Gateway", "ci": "CI-GW-EDGE-NODES", "count": 6,
        "severity": (0, 3, 3, 0), "hours": "peak",
        "titles": ["Gateway pods restarting during a traffic surge", "Connection resets at the edge during peak",
                   "Clients see dropped connections on the API"],
        "descriptions": ["Gateway pods were restarted during a traffic surge and clients saw dropped connections.",
                         "Clients reported connection resets from the public API for several minutes."],
        "symptoms": ["Pod eviction events", "Connection reset spikes"],
        "mitigation": "Raised the gateway memory limits and scaled out.",
        "logs": [("WARN", "PodEvicted", ["The node was low on resource: memory. Container edge-proxy was using 1.{n}Gi"]),
                 ("ERROR", "ConnectionReset", ["recv() failed (104: Connection reset by peer)"])],
        "rca": {
            "category": "Capacity / Resource Exhaustion",
            "summary": "Gateway pods were evicted because their memory request was far below real usage at peak.",
            "root_cause": "The gateway pods requested 512Mi but used close to 2Gi at peak because of large TLS session caches. Under node memory pressure Kubernetes evicted them first.",
            "whys": [("Why were connections dropped?", "Gateway pods were evicted."),
                     ("Why were they evicted?", "Nodes ran low on memory and the pods used more than they requested."),
                     ("Why was usage so high?", "TLS session caches grew with the number of clients."),
                     ("Why was the request so low?", "Resource requests were never updated after launch.")],
            "factors": {"Capacity": "Memory request far below usage.",
                        "Configuration": "TLS session cache without a size limit.",
                        "Monitoring": "No alert on requested versus used memory."},
            "corrective": "Set requests to real usage and capped the TLS session cache.",
            "preventive": "Monthly review of requested versus used resources for platform workloads.",
        },
    },
    {
        "key": "gw_ratelimit", "service": "API Gateway", "ci": "CI-GW-RATE-LIMITER", "count": 6,
        "severity": (0, 1, 4, 1), "hours": "business",
        "change": {"title": "Update API rate limiting policy", "type": "standard", "risk": "low",
                   "description": "Apply the new partner tier limits.", "ci": "CI-GW-RATE-LIMITER", "lead": (10, 120)},
        "titles": ["Partners throttled with HTTP 429", "API clients receive too many requests errors"],
        "descriptions": ["Legitimate partner traffic was throttled by the gateway although volumes were normal."],
        "symptoms": ["Unexpected 429 responses", "Rate limiter threshold breach"],
        "mitigation": "Adjusted the rate limits and cleared the limiter cache.",
        "logs": [("WARN", "RateLimited", ["Rate limit exceeded for client partner-{id} (limit 100 r/s)"])],
    },
    {
        "key": "gw_discovery", "service": "API Gateway", "ci": "CI-API-GATEWAY", "count": 5,
        "severity": (0, 2, 3, 0), "hours": "any",
        "titles": ["Gateway sending requests to stopped instances", "Connection refused errors behind the gateway"],
        "descriptions": ["The gateway briefly routed traffic to instances that had already been stopped."],
        "symptoms": ["Connection refused errors", "Stale endpoint routing"],
        "mitigation": "Forced a refresh of the service discovery cache.",
        "logs": [("ERROR", "ConnectionRefused", ["connect() failed (111: Connection refused) while connecting to upstream 10.42.3.{n}:8080"])],
    },
    # ---------------------------------------------------------------- Settlement Service
    {
        "key": "set_clearing", "service": "Settlement Service", "ci": "CI-CLEARING-HOUSE", "count": 8,
        "severity": (0, 3, 4, 1), "hours": "business", "vendor": True,
        "titles": ["Clearing house confirmations delayed", "Settlement confirmations waiting on the clearing house",
                   "Outgoing settlements not confirmed on time"],
        "descriptions": ["Connectivity to the external clearing house timed out intermittently and confirmations were delayed.",
                         "Treasury noticed that settlement confirmations were not arriving within the usual minutes."],
        "symptoms": ["External clearing house timeouts", "Settlement confirmation delay"],
        "mitigation": "Failed over to the backup clearing house connection.",
        "logs": [("ERROR", "ClearingTimeout", ["Session to clearing-house-link CLR-EU-01 timed out after 30s"]),
                 ("WARN", "ConfirmationDelay", ["{n} settlements waiting for confirmation longer than 10 minutes"])],
    },
    {
        "key": "set_duplicate", "service": "Settlement Service", "ci": "CI-SETTLE-SERVICE", "count": 5,
        "severity": (0, 2, 3, 0), "hours": "night",
        "titles": ["Duplicate settlement records in the ledger", "Ledger balance differs after nightly settlement"],
        "descriptions": ["A subset of settlement events was recorded twice in the ledger."],
        "symptoms": ["Duplicate settlement records", "Ledger balance mismatch"],
        "mitigation": "Removed the duplicates and added an idempotency check.",
        "logs": [("WARN", "DuplicateEvent", ["Settlement event SE-{id} already applied (offset {n})"])],
    },
    {
        "key": "set_rebalance", "service": "Settlement Service", "ci": "CI-KAFKA-CLUSTER", "count": 5,
        "severity": (0, 1, 3, 1), "hours": "any",
        "titles": ["Settlement processing throughput dropped", "Settlement events processed slowly",
                   "Settlement backlog growing slowly"],
        "descriptions": ["Settlement event processing slowed down and a backlog built up for a while.",
                         "Consumer lag on settlement events grew during the afternoon and recovered on its own."],
        "symptoms": ["Frequent rebalance events", "Processing throughput drop", "Consumer lag"],
        "mitigation": "Restarted the consumer group.",
        "logs": [("WARN", "ConsumerRebalance", ["Revoking previously assigned partitions [settlement-events-{n}]"]),
                 ("ERROR", "CommitFailed", ["CommitFailedException: the group has already rebalanced"])],
    },
    {
        "key": "set_recon", "service": "Settlement Service", "ci": "CI-SETTLE-DB", "count": 5,
        "severity": (0, 1, 3, 1), "hours": "night",
        "titles": ["Reconciliation mismatch after the nightly run", "Settlement and ledger totals do not match"],
        "descriptions": ["The nightly reconciliation flagged differences between settlement records and the ledger."],
        "symptoms": ["Reconciliation mismatch alert", "Ledger sync delay"],
        "mitigation": "Reran the reconciliation after correcting the sync offset.",
        "logs": [("WARN", "ReconMismatch", ["{n} settlement records missing from ledger snapshot"])],
    },
    {
        "key": "set_release", "service": "Settlement Service", "ci": "CI-SETTLE-SERVICE", "count": 5,
        "severity": (0, 1, 4, 0), "hours": "business",
        "change": {"title": "Deploy Settlement Service v{version}", "type": "normal", "risk": "medium",
                   "description": "Release with the new ledger export format.", "ci": "CI-SETTLE-SERVICE", "lead": (20, 120)},
        "titles": ["Settlement confirmations slower after release", "Settlement latency increase"],
        "descriptions": ["Settlement confirmation times increased shortly after the scheduled release."],
        "symptoms": ["Elevated settlement confirmation latency"],
        "mitigation": "Rolled back to the previous version.",
        "logs": [("WARN", "SlowProcessing", ["Batch of 500 events processed in {ms}ms (baseline 2100ms)"])],
    },
    # ---------------------------------------------------------------- Customer Portal
    {
        "key": "portal_checkout_js", "service": "Customer Portal", "ci": "CI-PORTAL-WEB", "count": 7,
        "severity": (0, 3, 3, 1), "hours": "business",
        "change": {"title": "Customer Portal release {version}", "type": "normal", "risk": "medium",
                   "description": "Frontend release with the new checkout layout.", "ci": "CI-PORTAL-WEB", "lead": (20, 180)},
        "titles": ["Checkout button not responding on some browsers", "Customers cannot finish checkout on Safari",
                   "Checkout abandonment jump on the portal"],
        "descriptions": ["The checkout button stopped responding for part of the customers, mostly on Safari.",
                         "Checkout abandonment doubled and customers reported that nothing happened when clicking pay."],
        "symptoms": ["Frontend click handler errors", "Checkout abandonment spike"],
        "mitigation": "Rolled back the frontend bundle.",
        "logs": [("ERROR", "FrontendError", ["TypeError: Cannot read properties of undefined (reading 'addEventListener') at checkout.js:1:48213"])],
    },
    {
        "key": "portal_search", "service": "Customer Portal", "ci": "CI-PORTAL-SEARCH", "count": 6,
        "severity": (0, 0, 3, 3), "hours": "any",
        "titles": ["Search results missing new products", "Portal search shows outdated results"],
        "descriptions": ["The portal search returned stale or missing results for a few hours."],
        "symptoms": ["Search index lag", "Missing product results"],
        "mitigation": "Triggered a manual index refresh.",
        "logs": [("WARN", "IndexLag", ["Search index lag {n} minutes (threshold 10)"])],
    },
    {
        "key": "portal_cart", "service": "Customer Portal", "ci": "CI-PORTAL-CART-CACHE", "count": 6,
        "severity": (0, 1, 3, 2), "hours": "any",
        "titles": ["Shopping cart shows outdated items", "Customers see items they already removed from the cart"],
        "descriptions": ["Some customers saw outdated shopping cart contents after changing their cart."],
        "symptoms": ["Cart data mismatch", "Cache invalidation errors"],
        "mitigation": "Flushed the cart cache.",
        "logs": [("ERROR", "CacheInvalidationFailed", ["Invalidation for cart C-{id} failed: timeout after 500ms"])],
    },
    {
        "key": "portal_slow", "service": "Customer Portal", "ci": "CI-PORTAL-WEB", "count": 7,
        "severity": (0, 2, 4, 1), "hours": "peak",
        "titles": ["Portal pages slow during the evening peak", "Slow page loads on the customer portal",
                   "Customer portal response time above target"],
        "descriptions": ["Portal pages loaded slowly for part of the users during a traffic peak.",
                         "Page load time went above five seconds for many customers in the evening."],
        "symptoms": ["Elevated page load time", "Frontend API timeout warnings"],
        "mitigation": "Scaled out the portal web tier.",
        "logs": [("WARN", "SlowRequest", ["GET /products took {ms}ms"]),
                 ("ERROR", "UpstreamTimeout", ["BFF call to api-gateway timed out after 8000ms"])],
    },
    {
        "key": "portal_personalisation", "service": "Customer Portal", "ci": "CI-PORTAL-CDN", "count": 4,
        "severity": (2, 2, 0, 0), "hours": "any",
        "change": {"title": "Update CDN caching rules for account pages", "type": "standard", "risk": "low",
                   "description": "Cache account page fragments at the edge to reduce origin load.", "ci": "CI-PORTAL-CDN", "lead": (30, 240)},
        "titles": ["Customers see another customer's name on the portal", "Wrong personal greeting shown on account pages"],
        "descriptions": ["Some customers saw another customer's name in the page header. No other personal data was shown."],
        "symptoms": ["Personalised content mismatch reports", "Privacy complaint"],
        "mitigation": "Purged the CDN cache and removed the new caching rule.",
        "logs": [("WARN", "CacheKeyWarning", ["Cached response for /account/header served to {n} different sessions"])],
        "rca": {
            "category": "Configuration Error",
            "summary": "A CDN rule cached a personalised page fragment and served it to other customers.",
            "root_cause": "The new caching rule stored the account header fragment without the session cookie in the cache key, so the first customer's greeting was served to others.",
            "whys": [("Why did customers see another name?", "The CDN served a cached header fragment."),
                     ("Why was it cached?", "A new rule cached account page fragments at the edge."),
                     ("Why was it shared?", "The cache key did not include the session."),
                     ("Why was it not caught?", "The rule was tested with a single test account.")],
            "factors": {"Change / Release": "New CDN caching rule.",
                        "Configuration": "Cache key without the session.",
                        "Process": "CDN rules raised as standard changes without a privacy review."},
            "corrective": "Removed the rule and purged the cache.",
            "preventive": "CDN rules on personalised paths now need a normal change and a test with two accounts.",
        },
    },
    {
        "key": "portal_login_loop", "service": "Customer Portal", "ci": "CI-PORTAL-WEB", "count": 4,
        "severity": (0, 1, 3, 0), "hours": "any",
        "change": {"title": "Update portal cookie domain configuration", "type": "standard", "risk": "low",
                   "description": "Move session cookies to the new portal domain.", "ci": "CI-PORTAL-WEB", "lead": (20, 180)},
        "titles": ["Login redirect loop on the customer portal", "Customers stuck between login and home page"],
        "descriptions": ["Some customers were sent back to the login page repeatedly after signing in."],
        "symptoms": ["Redirect loop reports", "Session cookie errors"],
        "mitigation": "Restored the previous cookie domain configuration.",
        "logs": [("WARN", "CookieRejected", ["Session cookie rejected: domain mismatch for {n} requests"])],
    },
    # ---------------------------------------------------------------- Notification Service
    {
        "key": "notif_sms", "service": "Notification Service", "ci": "CI-SMS-GATEWAY", "count": 7,
        "severity": (0, 2, 4, 1), "hours": "any", "vendor": True,
        "titles": ["SMS notifications not delivered", "Customers not receiving SMS alerts",
                   "SMS delivery failures for time-sensitive messages"],
        "descriptions": ["The SMS provider rejected messages and time-sensitive notifications were delayed.",
                         "Customers did not receive SMS alerts for about an hour."],
        "symptoms": ["SMS delivery failures", "Delivery confirmation timeouts"],
        "mitigation": "Failed over to the secondary SMS gateway.",
        "logs": [("ERROR", "SmsGatewayError", ["SMPP bind to sms-gateway-provider failed: ESME_RBINDFAIL"]),
                 ("WARN", "DeliveryReceiptTimeout", ["{n} SMS without delivery receipt after 10 minutes"])],
        "rca": {
            "category": "Third-Party / Vendor",
            "summary": "The SMS provider rejected our connections after rotating its credentials on its side.",
            "root_cause": "The SMS provider enforced new bind credentials after a security incident on its side. The notice reached a shared mailbox that nobody watched, so our workers kept using the old password.",
            "whys": [("Why were SMS not delivered?", "The provider rejected the connection (bind failed)."),
                     ("Why was the bind rejected?", "The provider required new credentials."),
                     ("Why did we not have them?", "The notice went to an unmonitored mailbox."),
                     ("Why unmonitored?", "Vendor contacts were never updated after the team reorganisation.")],
            "factors": {"Dependencies": "Single SMS provider without automatic failover.",
                        "Process": "Vendor notices sent to an unowned mailbox.",
                        "Monitoring": "Bind failures logged but not alerted."},
            "corrective": "Updated the credentials and enabled automatic failover to the secondary provider.",
            "preventive": "Vendor contact list reviewed every quarter; bind failures now page the on-call engineer.",
        },
    },
    {
        "key": "notif_push", "service": "Notification Service", "ci": "CI-PUSH-PROVIDER", "count": 6,
        "severity": (0, 0, 3, 3), "hours": "business", "vendor": True,
        "titles": ["Push notifications rejected by the provider", "Mobile push messages delayed"],
        "descriptions": ["The mobile push provider started rejecting part of the messages during a large send."],
        "symptoms": ["Push delivery failures", "Provider 429 responses"],
        "mitigation": "Reduced the push send rate and staggered the batches.",
        "logs": [("WARN", "ProviderThrottled", ["Push provider returned 429 QUOTA_EXCEEDED for {n} messages"])],
    },
    {
        "key": "notif_template", "service": "Notification Service", "ci": "CI-NOTIF-TEMPLATES", "count": 6,
        "severity": (0, 1, 4, 1), "hours": "business",
        "change": {"title": "Publish updated notification templates", "type": "standard", "risk": "low",
                   "description": "Publish the new order and shipping templates.", "ci": "CI-NOTIF-TEMPLATES", "lead": (10, 90)},
        "titles": ["Notifications failing to render", "Order e-mails not sent to customers"],
        "descriptions": ["A subset of notifications failed before sending because the message could not be built."],
        "symptoms": ["Template rendering errors", "Delivery failure spike"],
        "mitigation": "Reverted the template configuration.",
        "logs": [("ERROR", "TemplateError", ["Missing variable 'first_name' in template order_shipped_v{n}"])],
    },
    {
        "key": "notif_unsub", "service": "Notification Service", "ci": "CI-NOTIF-WORKER", "count": 4,
        "severity": (0, 1, 2, 1), "hours": "any",
        "titles": ["Unsubscribed users received marketing messages", "Marketing e-mails sent to opted-out customers"],
        "descriptions": ["A small number of customers who had unsubscribed received a marketing message."],
        "symptoms": ["Unsubscribe list staleness", "Compliance complaint report"],
        "mitigation": "Forced a resync of the unsubscribe list.",
        "logs": [("WARN", "SyncLag", ["Unsubscribe list last synced {n} hours ago"])],
    },
    {
        "key": "notif_consumer", "service": "Notification Service", "ci": "CI-NOTIF-WORKER", "count": 5,
        "severity": (0, 1, 3, 1), "hours": "any",
        "titles": ["Notification delivery backlog", "Notifications delayed by more than an hour"],
        "descriptions": ["Notifications were delayed while the queue kept growing."],
        "symptoms": ["Notification delay", "Queue depth growth"],
        "mitigation": "Restarted the notification workers.",
        "logs": [("ERROR", "ConsumerCrash", ["Worker exited with code 1: unhandled promise rejection in sendBatch"]),
                 ("WARN", "QueueDepth", ["Queue notifications.outbound depth {n}"])],
    },
    # ---------------------------------------------------------------- Payroll Service
    {
        "key": "payroll_bank", "service": "Payroll Service", "ci": "CI-BANK-SFTP", "count": 6,
        "severity": (1, 3, 2, 0), "hours": "business", "vendor": True,
        "titles": ["Bank transfer file not delivered", "Salary transfer file upload failed",
                   "Payroll bank export stuck"],
        "descriptions": ["The scheduled bank transfer file was not delivered to the bank for one payroll run.",
                         "Payroll Operations noticed that the bank had not received the salary transfer file."],
        "symptoms": ["Bank export job failure", "Delayed salary transfer"],
        "mitigation": "Regenerated the file and delivered it to the bank manually.",
        "logs": [("ERROR", "SftpUploadFailed", ["Upload to bank-transfer-sftp failed: Auth fail"])],
        "rca": {
            "category": "Certificate / Credential Expiry",
            "summary": "The SSH key used to upload the salary file to the bank expired.",
            "root_cause": "The bank enforces yearly SSH key expiry. The key was renewed by hand every year and the renewal was forgotten after the owner left the team.",
            "whys": [("Why was the file not delivered?", "The upload to the bank failed with an authentication error."),
                     ("Why did authentication fail?", "The SSH key had expired."),
                     ("Why was it not renewed?", "Renewal was a manual yearly task."),
                     ("Why was it forgotten?", "The task belonged to one person who left the team.")],
            "factors": {"Process": "Manual yearly renewal with a single owner.",
                        "Monitoring": "No expiry alert for bank credentials.",
                        "Dependencies": "Bank enforces key expiry."},
            "corrective": "Renewed the key and delivered the file.",
            "preventive": "Bank credentials added to the certificate expiry monitoring with 30 days warning.",
        },
    },
    {
        "key": "payroll_tax", "service": "Payroll Service", "ci": "CI-PAYROLL-APP", "count": 6,
        "severity": (0, 2, 3, 1), "hours": "business",
        "change": {"title": "Load new tax withholding tables", "type": "standard", "risk": "low",
                   "description": "Load the withholding tables published by the tax authority.", "ci": "CI-PAYROLL-APP", "lead": (120, 1440)},
        "titles": ["Payslips show incorrect withholding amounts", "Employees report wrong tax on payslips"],
        "descriptions": ["A subset of payslips used the wrong tax withholding amounts."],
        "symptoms": ["Incorrect withholding amounts", "Payslip correction requests"],
        "mitigation": "Reloaded the correct withholding table and reissued the payslips.",
        "logs": [("WARN", "WithholdingTableVersion", ["Payslip P-{id} calculated with table version 2.{n}"])],
    },
    {
        "key": "payroll_leave", "service": "Payroll Service", "ci": "CI-PAYROLL-APP", "count": 5,
        "severity": (0, 0, 2, 3), "hours": "business",
        "titles": ["Leave balances slightly wrong for some employees", "Employees report incorrect holiday balance"],
        "descriptions": ["Leave balances were slightly incorrect for some employees after the monthly accrual."],
        "symptoms": ["Leave balance discrepancy reports"],
        "mitigation": "Recalculated the affected balances.",
        "logs": [("WARN", "AccrualMismatch", ["Accrual for employee E-{id} differs from policy by 0.5 days"])],
    },
    {
        "key": "payroll_report", "service": "Payroll Service", "ci": "CI-PAYROLL-DB", "count": 5,
        "severity": (0, 0, 3, 2), "hours": "night",
        "titles": ["Monthly payroll report generated late", "Payroll reports not ready in the morning"],
        "descriptions": ["The monthly payroll report generation ran well behind schedule."],
        "symptoms": ["Report generation backlog", "Database query latency increase"],
        "mitigation": "Reduced the number of concurrent report jobs.",
        "logs": [("WARN", "SlowQuery", ["Payroll report query took {ms}ms"])],
    },
    # ---------------------------------------------------------------- User Profile Service
    {
        "key": "up_avatar", "service": "User Profile Service", "ci": "CI-AVATAR-STORAGE", "count": 6,
        "severity": (0, 0, 3, 3), "hours": "any",
        "titles": ["Profile picture uploads failing", "Customers cannot change their profile photo"],
        "descriptions": ["Profile picture uploads failed for part of the users."],
        "symptoms": ["Avatar upload errors", "Storage provider timeouts"],
        "mitigation": "Retried uploads through the secondary storage endpoint.",
        "logs": [("ERROR", "StorageTimeout", ["PUT avatars/{id}.jpg to avatar-object-storage timed out after 30s"])],
    },
    {
        "key": "up_duplicate", "service": "User Profile Service", "ci": "CI-USER-PROFILE-DB", "count": 5,
        "severity": (0, 1, 3, 1), "hours": "peak",
        "titles": ["Duplicate customer profiles created at signup", "Customers with two profiles after registering"],
        "descriptions": ["Some customers ended up with two profiles after registering during a busy period."],
        "symptoms": ["Duplicate profile ID reports", "Data merge requests"],
        "mitigation": "Merged the duplicate profiles.",
        "logs": [("WARN", "DuplicateEmail", ["Second profile created for e-mail hash {id}"])],
    },
    {
        "key": "up_latency", "service": "User Profile Service", "ci": "CI-USER-PROFILE-CACHE", "count": 6,
        "severity": (0, 1, 4, 1), "hours": "peak",
        "titles": ["Profile lookups slow during peak", "Account page slow to load customer details"],
        "descriptions": ["Profile lookup requests slowed noticeably during a traffic peak."],
        "symptoms": ["Elevated lookup latency", "Cache miss rate increase"],
        "mitigation": "Warmed the profile cache and scaled the service.",
        "logs": [("WARN", "CacheMiss", ["Profile cache hit ratio {pct}% (target 90%)"])],
    },
    {
        "key": "up_release", "service": "User Profile Service", "ci": "CI-USER-PROFILE-APP", "count": 5,
        "severity": (0, 2, 3, 0), "hours": "business",
        "change": {"title": "Deploy User Profile Service v{version}", "type": "normal", "risk": "medium",
                   "description": "Release with the new address validation.", "ci": "CI-USER-PROFILE-APP", "lead": (20, 120)},
        "titles": ["Profile updates failing after deployment", "Customers cannot save their address"],
        "descriptions": ["A fraction of profile update requests failed shortly after the scheduled deployment."],
        "symptoms": ["HTTP 500 responses from User Profile Service"],
        "mitigation": "Rolled back to the previous version.",
        "logs": [("ERROR", "ValidationServiceError", ["Address validation client returned 500 for country {id}"])],
    },
    # ---------------------------------------------------------------- Reporting Service
    {
        "key": "rep_stale", "service": "Reporting Service", "ci": "CI-REP-INGEST", "count": 7,
        "severity": (0, 0, 4, 3), "hours": "night",
        "titles": ["Reports show data from the previous day", "Morning finance reports outdated",
                   "Dashboards not refreshed overnight"],
        "descriptions": ["Generated reports contained stale data after the overnight ingestion ran late.",
                         "Finance teams found that the morning dashboards still showed the previous day."],
        "symptoms": ["Data staleness alert", "Ingestion pipeline delay"],
        "mitigation": "Reprocessed the delayed ingestion batch.",
        "logs": [("WARN", "IngestionLag", ["Ingestion lag {n} minutes for topic ledger-events"])],
    },
    {
        "key": "rep_cache_storm", "service": "Reporting Service", "ci": "CI-REP-CACHE", "count": 5,
        "severity": (0, 1, 3, 1), "hours": "business",
        "titles": ["Dashboards slow and warehouse CPU at 100%", "All dashboards slow at the same time"],
        "descriptions": ["Every dashboard slowed down at the same moment and the warehouse CPU reached its limit."],
        "symptoms": ["Simultaneous cache miss spike", "Database CPU spike"],
        "mitigation": "Restored the cache and enabled request coalescing.",
        "logs": [("WARN", "CacheStampede", ["{n} concurrent recomputations of dashboard finance_daily"])],
        "rca": {
            "category": "Software Defect",
            "summary": "A cache clearing bug made every dashboard recompute at the same time and overloaded the warehouse.",
            "root_cause": "A release changed the cache key prefix, so all cached dashboards were invalid at once. Hundreds of users triggered the same heavy queries in parallel.",
            "whys": [("Why were dashboards slow?", "The warehouse CPU was at 100%."),
                     ("Why?", "Hundreds of identical heavy queries ran in parallel."),
                     ("Why in parallel?", "All caches became invalid at the same moment."),
                     ("Why at once?", "A release changed the cache key prefix.")],
            "factors": {"Change / Release": "Cache key prefix changed in a release.",
                        "Capacity": "Warehouse sized for cached traffic only.",
                        "Configuration": "No request coalescing."},
            "corrective": "Enabled request coalescing so one query serves all waiting users.",
            "preventive": "Cache key changes now warm the new cache before switching.",
        },
    },
    {
        "key": "rep_export", "service": "Reporting Service", "ci": "CI-REP-APP", "count": 5,
        "severity": (0, 0, 3, 2), "hours": "night",
        "titles": ["Scheduled exports slow down other reports", "Report queue stuck behind a large export"],
        "descriptions": ["A large scheduled export used most of the memory and slowed down other reports."],
        "symptoms": ["Memory pressure alerts", "Report queue backlog"],
        "mitigation": "Split the large export into smaller jobs.",
        "logs": [("WARN", "MemoryPressure", ["Heap usage {pct}% on reporting-batch worker"])],
    },
    {
        "key": "rep_query", "service": "Reporting Service", "ci": "CI-REP-WAREHOUSE", "count": 5,
        "severity": (0, 0, 3, 2), "hours": "business",
        "titles": ["Report queries timing out", "Finance reports failing with timeouts"],
        "descriptions": ["Report generation queries exceeded their timeout for part of the morning."],
        "symptoms": ["Query timeout spike", "Database CPU pressure"],
        "mitigation": "Reduced the number of concurrent report queries.",
        "logs": [("ERROR", "QueryTimeout", ["Query canceled due to statement timeout (report R-{id})"])],
    },
]
